### ISSUE TITLE
Hover events not detected on widgets

### ISSUE THREAD

**Issue by kaamui** [letsfindaway/OpenBoard#49] opened 2021-09-01 13:23 UTC
_Starting reviewing your work, I will use your issues tracker to maintain some homogeneity. Tell me if you want me to respect some guidelines._ 

tested on Ubuntu 20.04, refactor-webengine branch, with a standard Qt 5.15.2 install (did not change the webengine version (note for myself : https://www.qt.io/blog/building-qt-webengine-against-other-qt-versions))

It seems hover events are not triggered (cursor style not changing, :hover effects not displayed). 

Maybe it has to be handled through QGraphicsProxyWidget (emit corresponding js events when detected on the widget ?) ? 

Example with 1.6.1 and qtwebkit, hovering the "english" link, using webbrowser app on wikipedia.org : 
![Capture d’écran du 2021-09-01 15-13-14](https://user-images.githubusercontent.com/11720903/131677617-b26f332b-9693-4e7b-a69b-bd5252ee4f11.png)

**Comment by letsfindaway** [comment] 2021-09-01 15:40
Your issues are perfect for me! I will first sort them to the project and then look into them step by step. Thanks for providing that feedback. It is exactly what I need: somebody else trying different things, which I missed or did not test.

**Comment by letsfindaway** [comment] 2021-09-01 18:54
Confirmed.

Hover works in the web browser and even in the Embed Controller, but not in a widget.

**Comment by letsfindaway** [comment] 2021-09-26 08:35
On widgets it depends on the selected tool whether hover events are detected or not: They work when the drawing tool is selected, but not when pointer or hand tool is active.

**Comment by letsfindaway** [comment] 2021-09-26 12:03
If I remove the check for the drawing tool in

https://github.com/letsfindaway/OpenBoard/blob/7e323b178556530ac2479644c3fe0eabf7fe230c/src/board/UBBoardView.cpp#L1155

then this issue and #50 are resolved, hovering for every tool used. Check the event handling further.

**Comment by kaamui** [comment] 2021-09-27 06:38
```
commit a672c9bf1c3d01310aa860b94a09362dd15f2f78
Author: Ilia Ryabokon <ilin@scand.com>
Date:   Mon May 20 16:21:52 2013 +0300

    Presentation changes

diff --git a/src/board/UBBoardView.cpp b/src/board/UBBoardView.cpp
--- a/src/board/UBBoardView.cpp
+++ b/src/board/UBBoardView.cpp
@@ -1108,134 +1102,138 @@
 void
 UBBoardView::mouseMoveEvent (QMouseEvent *event)
 {
     static QTime lastCallTime;
     if (!lastCallTime.isNull()) {
         qDebug() << "time interval is " << lastCallTime.msecsTo(QTime::currentTime());
     }
 
   QTime mouseMoveTime = QTime::currentTime();
-  if(!mIsDragInProgress && ((mapToScene(event->pos()) - mLastPressedMousePos).manhattanLength() < QApplication::startDragDistance()))
-  {
+  if(!mIsDragInProgress
+          && ((mapToScene(event->pos()) - mLastPressedMousePos).manhattanLength() < QApplication::startDragDistance())) {
+      qDebug() << "mouse move event canceled";
       return;
   }
 
   mIsDragInProgress = true;
-  UBStylusTool::Enum currentTool = (UBStylusTool::Enum)UBDrawingController::drawingController ()->stylusTool ();
-
+  mWidgetMoved = true;
   mLongPressTimer.stop();
 
-  if (isAbsurdPoint (event->pos ()))
-    {
+  if (isAbsurdPoint (event->pos ())) {
       event->accept ();
       return;
-    }
+  }
 
-  if (currentTool == UBStylusTool::Hand && (mMouseButtonIsPressed || mTabletStylusIsPressed))
-    {
+  if ((UBDrawingController::drawingController()->isDrawingTool())
+    && !mMouseButtonIsPressed) {
+      QGraphicsView::mouseMoveEvent(event);
+  }
+
+  int currentTool = static_cast<int>(UBDrawingController::drawingController()->stylusTool());
+  switch (currentTool) {

```

I don't understand either why it was introduced. 

I recently changed some lines concerning QGraphicsView::mouseMoveEvent calls to fix an issue with objects jumping to previous position. I've now the same behavior (hovering effects not applying) on the dev branch. Next commit should fix it for both your branch and mine.

**Comment by letsfindaway** [comment] 2021-09-27 16:46
Thanks for the clarification! I will rebase my branch on top of your correction, so that this issue is also solved with my branch.

**Comment by kaamui** [comment] 2022-10-20 14:43
This issue came back I think

**Comment by letsfindaway** [comment] 2022-10-21 05:34
> This issue came back I think

For me hover events work in the Browser, in the TrapFlash dialog and in a widget. Checked with www.wikipedia.org. However the tool tips displayed next to the language are black on a widget, while they work correct on the browser:
![grafik](https://user-images.githubusercontent.com/35591413/197120129-4f00610d-4152-41e5-9890-a07b04584c11.png)
Hover events work for me regardless of the tool selected. I will create a new issue for that. Probably I can fix this together with the transparency issue #107.

Any more information on how to reproduce your problem?

**Comment by letsfindaway** [comment] 2022-10-21 05:52
> For me hover events work in the Browser, in the TrapFlash dialog and in a widget. Checked with [www.wikipedia.org](http://www.wikipedia.org). However the tool tips displayed next to the language are black on a widget, while they work correct on the browser:

Black tool tips have been introduced by the commit trying to fix the transparent background. Fixed in this commit.

Remark: Tool tips only appear on the control screen, they are not rendered on the display screen. This is however probably related to the separate rendering of the display view. The hover event is however correctly transferred to the display screen.

**Comment by kaamui** [comment] 2022-11-01 13:06
Sorry I should have been more precise. The issue that came back is that the cursor is not updated according hover events

**Comment by letsfindaway** [comment] 2022-11-05 14:07
> Sorry I should have been more precise. The issue that came back is that the cursor is not updated according hover events

I think you have to be even more precise ;) What do you observe in which mode? What do you expect?

**Comment by kaamui** [comment] 2022-11-05 14:09
The cursor is not updated. Above a link, for example, the cursor remains a selector where it should be (when not explicitely forbidden by some css) a pointer, etc

**Comment by letsfindaway** [comment] 2022-11-05 15:23
The behavior very much depends on the tool selected. I have Wikipedia in a widget and see the following:

- When **Pen**, **Marker** or **Line** tool is selected, 
  - the cursor stays the same when entering the widget area. 
  - Hover effects appear, but the cursor does not change over a link. 
  - When pressing the mouse button, the tool function is applied.
- When the **Eraser**, **Hand**, Zoom in** or **Zoom out** tool is selected, 
  - the cursor stays the same when entering the widget area. 
  - Hover effects do not appear and the cursor does not change over a link. 
  - When pressing the mouse button, the tool function is applied.
- When the **Arrow** tool is selected, 
  - the cursor stays the same when entering the widget area. 
  - Hover effects appear, but the cursor does not change over a link. 
  - When pressing the mouse button over a link, the link is followed.
- When the **Magic Finger** tool is selected, 
  - the cursor changes to an arrow when entering the widget area. 
  - Hover effects appear, but the cursor does not change over a link. 
  - When pressing the mouse button over a link, the link is followed.

And I have no clue why this is.

**Comment by letsfindaway** [comment] 2022-11-06 14:08
I have now a proposal for a fix in branch [`fix-widget-cursor`](https://github.com/letsfindaway/OpenBoard/tree/fix-widget-cursor). This branch fixes the issue with the cursor over links in a web widget by listening to the `linkHovered` signal and switching the cursor accordingly.

Note however that with the "play" tool the cursor will be the pointing finger in all cases, as this is already the cursor used for the play tool. So this fix is mainly when using the selector tool. Do you think the cursor should change to an arrow when entering the widget? I'm not sure whether this would be a better user experience.

We will however still have a hover effect when moving a drawing tool over a link with an associated hover effect. This is caused by forwarding mouse move events to the widget when such a tool is used. That is necessary especially for the ruler and triangle to detect the mouse entering and leaving the tool.

See also comment https://github.com/letsfindaway/OpenBoard/issues/49#issuecomment-927293865 in this discussion. The reason for forwarding these events is exactly the ruler. And it is not easy to distinguish the cases here. Do you think this is a problem?

**Comment by kaamui** [comment] 2022-11-06 14:34
There are a lot of values for the CSS property cursor (https://www.w3schools.com/cssref/tryit.php?filename=trycss_cursor). The ultimate goal is to have them interpreted in the web widget as they are in the navigator, without the need to explicitely handle each one on our side. I wonder if it's related to some events not passing through proxy widget for example. 

Expect this issue of `cursor` CSS property being totally ignored, the other points you mentionned are OK for me, and less important as it does not affect much user experience (at least from my pov)

**Comment by letsfindaway** [comment] 2022-11-07 14:04
Thanks for the link to the w3schools web page. Yes, indeed, this should work.

For some events not passed through: We're just moving the mouse, so I don't see what other events would be needed. I also tried to unset all cursors o surrounding items or widgets - no success.

Next I will try to create a minimal example with a web view in a QGraphicsProxyWidget and nothing else around, no event filtering etc and see what happens.

**Comment by letsfindaway** [comment] 2022-11-07 15:58
> Next I will try to create a minimal example with a web view in a QGraphicsProxyWidget and nothing else around, no event filtering etc and see what happens.

The same occurs in a very minimal example with a `QWebEngineView` in a `QGraphicsProxyWidget` as follows (just the relevant part):

```c++
MainWindow::MainWindow(QWidget *parent)
    : QMainWindow(parent)
    , ui(new Ui::MainWindow)
{
    ui->setupUi(this);

    QGraphicsScene* scene = new QGraphicsScene();
    QGraphicsProxyWidget* proxy = new QGraphicsProxyWidget();
    QWebEngineView* view = new QWebEngineView();
    proxy->setWidget(view);
    scene->addItem(proxy);
    proxy->setPos(-400, -300);
    proxy->resize(800, 600);
    proxy->setVisible(true);
    ui->graphicsView->setScene(scene);
    view->load(QUrl("https://www.w3schools.com/cssref/tryit.php?filename=trycss_cursor"));
}
```

I just created a default application in QtCreator, added a `QGraphicsView` to the central widget and added this code.

So it seems to be an issue with the `QGraphicsProxyWidget`.

**Comment by letsfindaway** [comment] 2022-11-08 07:13
I think this is now a new issue, not related to the original one.

I could create a Github project with my proof-of-failure and create a QTBUG report. What do you think?

**Comment by kaamui** [comment] 2022-11-09 07:55
I think it's a really good idea !

**Comment by letsfindaway** [comment] 2022-11-09 07:56
I now think that this behavior is intended by the Qt developers. Just consider that a `QGraphicsItem` can be transformed, i.e. scaled, rotated, sheard etc. If the cursor would actually belong to the `QWebEngineView` embedded in the item, then the cursor would also have to be transformed.

A cursor is however a fixed-size graphical element, typically drawn by the underlying window system. So it more belongs to the screen, or an area of the screen.

So the Qt developers are here in a dilemma: If we implement what the CSS specification tells, then we would have to draw the cursor on our own, so that it can be transformed. If we stick to the cursor being a fixed-size graphical element drawn even outside of Qt, then we cannot fulfill the CSS specification. They apparently have chosen the latter, and in fact I think this is the better choice.

For OpenBoard this means that the best we can do is something like I tried to do in branch [fix-widget-cursor](https://github.com/letsfindaway/OpenBoard/tree/fix-widget-cursor). We can still think about how to handle this in detail.

**Comment by kaamui** [comment] 2022-11-09 08:05
I'm not sure about that. With the Webkit, it was working correctly, without the need of a `QGraphicsProxyWidget` (thus performances were a bit better too), and I never experienced any conflicts where handling the cursor (like it's done in simplebrowser) would create undesired behavior. Also, `QGrapchisItem` transformations imply that the cursor leaves the QGraphicsItem area during transformation

**Comment by kaamui** [comment] 2022-11-09 08:12
> For OpenBoard this means that the best we can do is something like I tried to do in branch [fix-widget-cursor](https://github.com/letsfindaway/OpenBoard/tree/fix-widget-cursor). We can still think about how to handle this in detail

If we had to go for this workaround in the end (and we probably will even if Qt agree to do something on this issue, because it will take a long time before it hits a new Qt version), `pointer` and `text` should be enough to make the user experience a bit better.

**Comment by kaamui** [comment] 2022-11-09 09:24
> So the Qt developers are here in a dilemma: If we implement what the CSS specification tells, then we would have to draw the cursor on our own, so that it can be transformed. If we stick to the cursor being a fixed-size graphical element drawn even outside of Qt, then we cannot fulfill the CSS specification. They apparently have chosen the latter, and in fact I think this is the better choice.

Also, when you look at qcursor.h, it doesn't look like a QCursor could be affected by any transformation other than translation.

**Comment by letsfindaway** [comment] 2022-11-09 09:42
In my proof-of-failure I found out that if I right-click on one of the styled texts to show the context menu and then right-click again (or click somewhere else) to hide it and the move the mouse, the cursor is shown as defined by the CSS style. So you might be right that it should work, but just some events are not properly handled in the Proxy.

**Comment by kaamui** [comment] 2022-11-09 09:43
Wow ! That's a great finding !

**Comment by letsfindaway** [comment] 2022-11-09 09:45
And also if I move the mouse from outside of that little application _fast enough_ over one of the entries, that cursor appears. Strange thing is that _fast enough_.

**Comment by kaamui** [comment] 2022-11-09 09:46
I tried to replicate your minimal code, but I have really poor performances and can't remember or find how you did in OpenBoard to make widgets render correctly. I also remember that you finally didn't had to use the workaround given in a Qt forum page so ... how did you do this ? 😄

**Comment by letsfindaway** [comment] 2022-11-09 09:59
I checked in that project. See https://github.com/letsfindaway/WebWidgetCursor

**Comment by kaamui** [comment] 2022-11-09 10:00
Great, thanks.

**Comment by letsfindaway** [comment] 2022-11-09 10:28
I have now also created a bug report: https://bugreports.qt.io/browse/QTBUG-108284

**Comment by kaamui** [comment] 2022-11-09 10:31
you can add Qt 6.4.0 (I'm working on it right now) on affected versions

**Comment by letsfindaway** [comment] 2022-11-09 16:09
See my branch https://github.com/letsfindaway/WebWidgetCursor/tree/workaround and https://bugreports.qt.io/browse/QTBUG-108284?focusedCommentId=689642&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-689642 for a workaround. I will try to transfer this to OpenBoard.

**Comment by letsfindaway** [comment] 2022-11-10 07:50
Again closed as workaround was merged with PR 705

**Closed by letsfindaway** 2022-11-10 07:50 UTC
Labels: bug

**Comment by kaamui** [comment] 2022-11-10 10:16
The workaround is working well for me to with 6.2.4, but has no effect with 6.4.0.

Maybe a different webengine version in 6.4 ? I wonder if I should report it on [QTBUG-108284](https://bugreports.qt.io/browse/QTBUG-108284)

**Comment by letsfindaway** [comment] 2022-11-10 10:23
Yes, please report there.

I just found out by experimenting that the `CursorChange` event shows up at the associated `QWindow`. This is of course nowhere documented and could easily have changed. In this case we would have to look for another source of that event. But this was not easy, as most classes have been quite internal stuff with no access from outside. So I was happy when I found the `QWindow`.

**Comment by letsfindaway** [comment] 2022-11-10 17:06
I just downloaded Qt 6.4 and tried my minimum example with that. I get crazy things:

![grafik](https://user-images.githubusercontent.com/35591413/201159950-c48b0d11-1bdb-47ff-b6c8-0eff79ebcbd5.png)

There are two windows of identical size. One shows the browser, the other the content of the underlying screen just as a screenshot. When I move this screenshot window to the front and move the mouse over the right part, then the cursor shape changes as if I would move it over the other window. On the screenshot you see the "Cell" cursor.

The events can still be intercepted at view->windowHandle().

Do you a have any other strange effects with Qt 6.4?

**Comment by kaamui** [comment] 2022-11-11 07:40
Nope, pretty similar except the second windows shows a white background instead of a screenshot of what's behind (tested on Windows). And performances that are pretty as I already noted.  

When I tried to replicate your minimal code, I had the exact same issue and though I had done something wrong with the ui, but encountered the same issues with yours.
