### ISSUE TITLE
[Interactivities] Train is not loading

### ISSUE THREAD

**Issue by kaamui** [letsfindaway/OpenBoard#54] opened 2021-09-01 13:50 UTC
`Uncaught (in promise) TypeError: Cannot read property 'async' of undefined` showed up on console output.

@letsfindaway I know you worked on Train interactivity, especially, and regarding your messages on it, you didn't experienced it so I might have missed something (maybe I'm on the wrong branch, but I doubt it).

**Comment by letsfindaway** [comment] 2021-09-01 19:16
Could not reproduce on first try, will further analyze it.

**Comment by letsfindaway** [comment] 2021-09-03 13:48
Now that you know how to invoke the Web Inspector (see #51): Could you please try this again and look for the console messages? Also file and line are important to know.

**Comment by kaamui** [comment] 2022-04-28 09:51
Cannot reproduce it anymore (tested on 20.04)

**Comment by letsfindaway** [comment] 2022-04-28 10:12
Closed as no longer reproducible

**Closed by letsfindaway** 2022-04-28 10:12 UTC
Labels: bug, analyze, cannot reproduce
